apiVersion: v1
kind: Service
metadata:
  name: insight-frontend
  namespace: insight-healthcare
  labels:
    app: insight-healthcare
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: insight-healthcare
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
